### PR TITLE
Bug fixes in recent commits + more future-proof code

### PR DESCRIPTION
**Pull request by tacsipacsi**
Bug fixes:
- `tl_from_namespace` remains `tl_from_namespace`, in the `templatelinks` table.  The new `linktarget` table contains data about link *targets*, not link *sources*.
- The `globalimagelinks` table needs to be queried from the `commonswiki.labsdb` database server, not the from the one for the wiki specified by the user.

More future-proof code:
- Query the link target ID separately. Yields slightly worse performance for now, but will probably have better performance once all tables are migrated to the new system, since the `linktarget` table will need to be queried only once. It also reduces code repetition.
- Add TODOs for the Phabricator tasks to keep an eye on (`pagelinks` and `imagelinks` table migration).
- Instead of the C-style “-1 means error, check after each function call”, introduce an exception class that can be thrown at one place and caught at another place, travelling through the call stack.
- Introduce type declarations [1]. This requires PHP 7.1+, but I really hope no one wants to use such old PHP versions. :)

[1] https://www.php.net/manual/en/language.types.declarations.php

### CODE REVIEW

**Comment by ebraminio** [comment]
Unfortunately `FastCGI-stderr: PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in index.php on line 27` :/ Can you provide some fix for it?

**Comment by tacsipacsi** [comment]
So it _does_ use PHP 7.0… :( See https://wikitech.wikimedia.org/wiki/Help:Toolforge/Web#Choosing_a_backend for how to select the runtime environment. I tested it with PHP 7.3 (`php7.3` Kubernetes backend), but it should work with PHP 7.4 (`php7.4`) as well. Or if you’d like me to do it, you can add me as a co-maintainer at https://toolsadmin.wikimedia.org/tools/id/linkscount/maintainers/ (it’s generally a best practice to have more than one maintainer, should anything happen to you). Speaking of best practices, documenting supported PHP version(s) e.g. in a `README` file would help avoid such issues in the future.

**Comment by ebraminio** [comment]
Oh sure thing, also gave the right in GitHub also :)

**Comment by tacsipacsi** [comment]
Thanks, now https://linkscount.toolforge.org/?namespace=0&p=Earth&fromNamespace=0&dbname=enwiki finally works on the all-new PHP 7.4!

**Comment by ebraminio** [comment]
@tacsipacsi Just wanted to let you know if you want to update the code on the server the next time, you can just issue `git pull` as this is cloned on the root of the tool also. Thanks :)

**Comment by ebraminio** [comment]
@tacsipacsi The tool is broken again, guess I need your help again but I'm also trying to fix it 😊

**Comment by ebraminio** [comment]
Fixed https://github.com/ebraminio/linkscount/commit/97de4683bab73ffe92db3b9f1263805d3200b45a thanks to your change here 😊

**Comment by tacsipacsi** [comment]
This fixed the tool on Commons, but broke it on Wikidata and a few large Wikipedias (enwiki, ptwiki, svwiki, thwiki, trwiki, zhwiki) 🙁 – and in a more subtle way: it doesn’t return zero, just a number potentially smaller than the reality. See https://lists.wikimedia.org/hyperkitty/list/cloud@lists.wikimedia.org/thread/KWWEWNFVXDXOHZBJO32NQLBKC5LUTEAB/#BU5Q4QRA3C73WPGT6APL3AWO2CSKQOSV. (The work seems to be tracked in https://phabricator.wikimedia.org/T351237.)

**Pull request merged**
